import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NotificationsProvider } from "@/components/feedback/NotificationsProvider";
import { CartProvider } from "@/hooks/useCart";
import { CartFloatingButton } from "@/components/cart/CartFloatingButton";
import { CartDrawer } from "@/components/cart/CartDrawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NotificationsProvider>
          <CartProvider>
            {children}
            <CartFloatingButton />
            <CartDrawer />
          </CartProvider>
        </NotificationsProvider>
      </body>
    </html>
  );
}
